### PR TITLE
Can I Join RocHack?

### PR DESCRIPTION
**Pull request by peterdfinn**
I added my name to the bottom of the list under "Class of 2016".  Are you open to recent graduates?  I got my Master's in Computer Science this past May.

### CODE REVIEW

**Comment by jthurst3** [comment]
Someone more familiar: how do you preview changes to the gh-pages branch? Also I thought because we have a gh-pages branch, you can view it by going to http://rochack.github.io (even if we already have rochack.org).

**Comment by jeremywrnr** [comment]
The preview link should be [rochack.github.io/rochack.org](https://rochack.github.io/rochack.org), but this also is set to forward to rochack.org, so I do not think there is a way to preview a specific set of changes on a non-published branch (though there could be some way to change this).

You can use [jekyll](http://jekyllrb.com/) to host the site locally, and then view the site on `localhost:4000/`.

@clehner may know more about how the site is hosted.

**Comment by jthurst3** [comment]
@peterdfinn I tested your changes out locally using Jekyll, and it seems that you inserted tabs before the dash and your name. This breaks the template and makes the about.html page render without any styling. Please convert the tabs to spaces and push this change to your local gh-pages branch. Let me know if you have any trouble.

**Comment by peterdfinn** [comment]
I just edited about.html as per your comment and pushed it to my forked gh-pages branch.  I've been trying to get Jekyll up and running in my local environment, and I can't run "bundle install" from my command line.  I also tried "/usr/local/bin/bundle install", but I ran into the same error both times:
`Could not locate Gemfile or .bundle/ directory`
I've been doing what I can to resolve this, but I have to put this down for a bit and work on something else.  I thought I'd write this to keep you up to date and see if there were any obvious easy fix that I simply didn't know about.

**Comment by jthurst3** [comment]
Looks great! Will merge it in.
Hmm... are you running the command from within the directory that has the Gemfile? Try that first (when you have time), then we can go from there. Hope to see you at the RocHack hacker nights this fall!

**Pull request merged**
